name: mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  auto_route: ^8.0.3
  table_calendar: ^3.0.9
  intl: ^0.18.1
  get_it:
  shared_preferences:
  dio:
  equatable:
  flutter_dotenv: ^5.1.0
  flutter_screenutil:
  dartz:
  flutter_bloc:
  bloc:
  salomon_bottom_bar:
  rxdart:
  top_snackbar_flutter: ^3.1.0
  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.1
  mime: ^1.0.5
  http_parser: ^4.0.2
  # flutter_native_splash: ^2.4.0
  latlong2: ^0.9.0
  flutter_map:
  flutter_map_cancellable_tile_provider:
  socket_io_client:
  geolocator:
  permission_handler:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^3.0.2
  auto_route_generator: ^8.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: fill

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
        - asset: assets/fonts/poppins/Poppins-Black.ttf
